name: Download File Workflow

on:
  push:
    paths:
      - 'file.txt'  # Trigger this workflow when your file is updated.

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.WORKFLOWS_ACTIONS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.WORKFLOWS_ACTIONS_PRIVATE_KEY }}

    - name: Download file
      run: |
        # Your commands to download or process the file.
        cat file.txt