on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Convert files structure to text
        run: |
          git ls-tree -r -t HEAD | awk '{ print $2 " " $4 }' > files.txt
      - name: Calculate sha256sum of folders containing .ows files
        run: |
          ./hashDir.sh ./RNA > hash.txt
          cat hash.txt
      - name: Commit and push generate files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add files.txt hash.txt
          git commit -m "Updated files.txt and hash.txt." || echo "No changes to commit"
          git push
