on:
  push:
    paths-ignore:
      - 'files.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WORKFLOWS_ACTIONS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - uses: actions/checkout@v3
      - name: Run github-to-json
        run: |
          npm install --global github-to-json
          github-to-json Biodepot-LLC workflows -t ${{ secrets.WORKFLOWS_ACTIONS_PRIVATE_KEY }} -o files.json
      - name: Commit changes
        run: |
          git config --global user.name "Thomas Dahlstrom"
          git config --global user.email "tdahlstrom@users.noreply.github.com"
          git add files.json
          git commit -m "Update files.json"
          git push
