on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Convert to JSON
        run: |
          git ls-tree -rt > files.txt
      - name: Commit and push file list
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add files.txt
          git commit -m "updated files.txt" || echo "No changes to commit"
          git push